apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-manager-rolebinding
subjects:
  - kind: ServiceAccount
    name: provider-controller-manager
    namespace: provider
roleRef:
  kind: ClusterRole
  name: provider-manager-role
  apiGroup: rbac.authorization.k8s.io