apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provider-controller-manager-binding
  namespace: provider
subjects:
  - kind: ServiceAccount
    name: provider-controller-manager
    namespace: provider
roleRef:
  kind: Role
  name: provider-controller-manager-role
  apiGroup: rbac.authorization.k8s.io